### ISSUE TITLE
Became a supporter after having run the ai-aimbot-setup and didnt receive the ability to automatically get dependencies until reinstalling through the installer 

### ISSUE THREAD

**Issue by janzpro1** [RootKit-Org/Launcher#2]
Became a supporter after having run the ai-aimbot-setup and didnt receive the ability to automatically get dependencies until reinstalling through the installer 

![kuva_2023-12-04_211125429](https://github.com/RootKit-Org/Launcher/assets/150056466/bf414d60-ed3f-48b1-a38b-40f5e9ee39cc)

**Comment by Qfc9** [comment]
Fixed
